// <auto-generated />
using System;
using BaseMinDE2026WEB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BaseMinDE2026WEB.Migrations
{
    [DbContext(typeof(DeWeb2026Context))]
    partial class DeWeb2026ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BaseMinDE2026WEB.Models.CourceTable", b =>
                {
                    b.Property<int>("IdCource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cource");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCource"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("IdCource")
                        .HasName("cource_table_pk");

                    b.ToTable("cource_table", (string)null);
                });

            modelBuilder.Entity("BaseMinDE2026WEB.Models.LoginTable", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("character varying")
                        .HasColumnName("login");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("password");

                    b.HasKey("Login")
                        .HasName("login_table_pk");

                    b.ToTable("login_table", (string)null);
                });

            modelBuilder.Entity("BaseMinDE2026WEB.Models.OrderStatusTable", b =>
                {
                    b.Property<int>("IdOrderStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_order_status");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOrderStatus"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("IdOrderStatus")
                        .HasName("order_status_table_pk");

                    b.ToTable("order_status_table", (string)null);
                });

            modelBuilder.Entity("BaseMinDE2026WEB.Models.OrderTable", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_order");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOrder"));

                    b.Property<int>("IdCourse")
                        .HasColumnType("integer")
                        .HasColumnName("id_course");

                    b.Property<int>("IdPaymentType")
                        .HasColumnType("integer")
                        .HasColumnName("id_payment_type");

                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("id_status");

                    b.Property<string>("Reviev")
                        .HasColumnType("character varying")
                        .HasColumnName("reviev");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("user");

                    b.HasKey("IdOrder")
                        .HasName("order_table_pk");

                    b.HasIndex("IdCourse");

                    b.HasIndex("IdPaymentType");

                    b.HasIndex("IdStatus");

                    b.HasIndex("User");

                    b.ToTable("order_table", (string)null);
                });

            modelBuilder.Entity("BaseMinDE2026WEB.Models.PaymentTypeTable", b =>
                {
                    b.Property<int>("IdPaymentType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_payment_type");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPaymentType"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("IdPaymentType")
                        .HasName("payment_type_table_pk");

                    b.ToTable("payment_type_table", (string)null);
                });

            modelBuilder.Entity("BaseMinDE2026WEB.Models.UserTable", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("character varying")
                        .HasColumnName("login");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Patronymic")
                        .HasColumnType("character varying")
                        .HasColumnName("patronymic");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("surname");

                    b.HasKey("Login")
                        .HasName("user_table_pk");

                    b.ToTable("user_table", (string)null);
                });

            modelBuilder.Entity("BaseMinDE2026WEB.Models.OrderTable", b =>
                {
                    b.HasOne("BaseMinDE2026WEB.Models.CourceTable", "IdCourseNavigation")
                        .WithMany("OrderTables")
                        .HasForeignKey("IdCourse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("order_table_cource_table_fk");

                    b.HasOne("BaseMinDE2026WEB.Models.PaymentTypeTable", "IdPaymentTypeNavigation")
                        .WithMany("OrderTables")
                        .HasForeignKey("IdPaymentType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("order_table_payment_type_table_fk");

                    b.HasOne("BaseMinDE2026WEB.Models.OrderStatusTable", "IdStatusNavigation")
                        .WithMany("OrderTables")
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("order_table_order_status_table_fk");

                    b.HasOne("BaseMinDE2026WEB.Models.UserTable", "UserNavigation")
                        .WithMany("OrderTables")
                        .HasForeignKey("User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("order_table_user_table_fk");

                    b.Navigation("IdCourseNavigation");

                    b.Navigation("IdPaymentTypeNavigation");

                    b.Navigation("IdStatusNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("BaseMinDE2026WEB.Models.UserTable", b =>
                {
                    b.HasOne("BaseMinDE2026WEB.Models.LoginTable", "LoginNavigation")
                        .WithOne("UserTable")
                        .HasForeignKey("BaseMinDE2026WEB.Models.UserTable", "Login")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_table_login_table_fk");

                    b.Navigation("LoginNavigation");
                });

            modelBuilder.Entity("BaseMinDE2026WEB.Models.CourceTable", b =>
                {
                    b.Navigation("OrderTables");
                });

            modelBuilder.Entity("BaseMinDE2026WEB.Models.LoginTable", b =>
                {
                    b.Navigation("UserTable");
                });

            modelBuilder.Entity("BaseMinDE2026WEB.Models.OrderStatusTable", b =>
                {
                    b.Navigation("OrderTables");
                });

            modelBuilder.Entity("BaseMinDE2026WEB.Models.PaymentTypeTable", b =>
                {
                    b.Navigation("OrderTables");
                });

            modelBuilder.Entity("BaseMinDE2026WEB.Models.UserTable", b =>
                {
                    b.Navigation("OrderTables");
                });
#pragma warning restore 612, 618
        }
    }
}
